locals {
  host_ip = zipmap(azurerm_public_ip.tfub_publicip[*].fqdn, azurerm_linux_virtual_machine.tfub_vm[*].public_ip_address)
  
  ansible_hosts_content = <<-EOT
    # ansible hosts test - generated by terraform from VM info
    [az_ubuntu]
    %{for index, h in azurerm_public_ip.tfub_publicip.*.fqdn~}
    server-${index} ansible_host=${h}
    %{endfor~}


    [amz_linux:vars]
    ansible_user=${var.ssh_user}

    [aws_servers:children]
    [az_ubuntu]
    EOT 

  test = <<-EOT1
    %{for fqdn, ip in local.host_ip~}
      DA HOST:${lower(fqdn)} DA IP: ${ip}
    %{endfor~}
  EOT1
}


resource "local_file" "ansible_hosts_inline" {
  ## Two ways to emulate a conditional ("If"): count and for_each 
  ## count "reads better"
  count = var.create_ansible_hosts ? 1 : 0
  #    for_each = toset(var.create_ansible_hosts ? ["hosts"]: [])

  content              = local.ansible_hosts_content
  file_permission      = "0644"
  directory_permission = "0644"
  # error if directory does not exist (appears to contradict documentation)
  filename = "${path.module}/ansible/ansible_hosts" 
  # filename ="/tmp/ansible/ansible_hosts"
}

resource "local_file" "foo" {
    content  = "foo!"
    filename = "${path.module}/foo.bar"
}
